version: "3"
services:
    postgres:
        image: postgres:10
        container_name: postgres
        restart: always
        environment: 
            - POSTGRES_USER=blog
            - POSTGRES_PASSWORD=testP@ssword
        ports: 
            - "54321:5432"
            
    blog:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: blog-api
        depends_on: 
            - postgres
        environment: 
            - DB_HOST=postgres
            - DB_PASSWORD=testP@ssword
            - API_HOST=app
            - PYTHONDONTWRITEBYTECODE=1 
        volumes: 
            - ./blog:/blog
            - ./test:/test
        ports: 
            - "5005:80"
